In [2]:
import numpy as np
d=np.array([1,2,3,4,5,6])
d[2]

3

In [3]:
arr=np.arange(start=1,stop=10,step=2)
arr

array([1, 3, 5, 7, 9])

In [4]:
arr2=np.arange(1,10,2)
arr2

array([1, 3, 5, 7, 9])

In [5]:
#convert 1-D array into 2-D array
arr2=arr2.reshape(5,1)
arr2

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [6]:
#convert 2-D array into 1-D array
arr2=arr2.reshape(-1)
arr2

array([1, 3, 5, 7, 9])

In [7]:
#convert 1-D array into 2-D array
arr2=arr2.reshape(-1,1)
arr2

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [9]:
arr3=np.array([1,2,3,4,5,6,7,8,9]) 
arr3=arr3.reshape(3,3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr3=arr3.reshape(-1,1)
arr3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [19]:
# arr4=np.array([1,2,3,4,5,6,7,8,9])
# arr4=arr4.reshape(3,3)
# arr5=np.array([1,2,3,4,5,6,7,8,9])
# arr5=arr5.reshape(3,3)
# (arr5+arr4)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [18]:
a=np.random.rand(3,2)  #generating an array filled with random values
a

array([[0.13368401, 0.18124464],
       [0.38522074, 0.11629112],
       [0.51945216, 0.22764112]])

In [20]:
d=np.ones((2,3))  #generating an array filled with 1's
d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
f=np.zeros((3,4))
f

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
f.dtype

dtype('float64')

In [29]:
for i in f:
    print(i)
    for j in i:
        print(j)

[0. 0. 0. 0.]
0.0
0.0
0.0
0.0
[0. 0. 0. 0.]
0.0
0.0
0.0
0.0
[0. 0. 0. 0.]
0.0
0.0
0.0
0.0


In [30]:
for i in f:
    for j in i:
        print(j)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [32]:
for i in np.nditer(f):
    print(i)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [34]:
#join 2 arraies.
arr7=np.array([1,2,3,4,5])
arr8=np.array([6,7,8,9,])
arr6=np.concatenate((arr7,arr8))
arr6

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr9=np.array([[3,4],[9,20]])
arr10=np.array([[23,24],[29,220]])
arr11=np.concatenate((arr9,arr10),axis=0) #joining 2 array vertically
arr11

array([[  3,   4],
       [  9,  20],
       [ 23,  24],
       [ 29, 220]])

In [38]:
arr11=np.concatenate((arr9,arr10),axis=1) #joining 2 array horizontally
arr11

array([[  3,   4,  23,  24],
       [  9,  20,  29, 220]])

In [40]:
arr11=np.append(arr11,[[12,13,14,15]],axis=0) #adding row at the end of the array
arr11

array([[  3,   4,  23,  24],
       [  9,  20,  29, 220],
       [ 12,  13,  14,  15]])

In [48]:
new_col=np.array([[56,78,89]])
new_col=new_col.reshape(3,1)
new_col


array([[56],
       [78],
       [89]])

In [47]:
arr11=np.append(arr11,new_col,axis=1) #adding column at the end of the array
arr11

array([[  3,   4,  23,  24,  56],
       [  9,  20,  29, 220,  78],
       [ 12,  13,  14,  15,  89]])

In [50]:
arr11=np.insert(arr11,1,[[90,91,92,93,94]],axis=0)
arr11

array([[  3,   4,  23,  24,  56],
       [ 90,  91,  92,  93,  94],
       [  9,  20,  29, 220,  78],
       [ 12,  13,  14,  15,  89]])

In [51]:
arr11=np.insert(arr11,1,[[91,92,93,94]],axis=1)
arr11

array([[  3,  91,   4,  23,  24,  56],
       [ 90,  92,  91,  92,  93,  94],
       [  9,  93,  20,  29, 220,  78],
       [ 12,  94,  13,  14,  15,  89]])

In [53]:
#delete function
arr11=np.delete(arr11,1,axis=0)  #deleting row at index 1
arr11

array([[  3,  91,   4,  23,  24,  56],
       [  9,  93,  20,  29, 220,  78],
       [ 12,  94,  13,  14,  15,  89]])

In [54]:
arr11=np.delete(arr11,2,axis=1)  #deleting column at index 2
arr11

array([[  3,  91,  23,  24,  56],
       [  9,  93,  29, 220,  78],
       [ 12,  94,  14,  15,  89]])

In [56]:
arr13=np.array([1,2,3,4])
arr14=np.array([9,8,7,6])
np.add(arr13,arr14)


array([10, 10, 10, 10])

In [57]:
np.subtract(arr13,arr14)

array([-8, -6, -4, -2])

In [58]:
np.multiply(arr13,arr14)

array([ 9, 16, 21, 24])

In [59]:
np.divide(arr13,arr14)

array([0.11111111, 0.25      , 0.42857143, 0.66666667])

In [60]:
np.remainder(arr13,arr14)

array([1, 2, 3, 4])

In [61]:
#Data types in numpy
arr16=np.array([1,2,3,4,5],dtype='i')
arr16

array([1, 2, 3, 4, 5], dtype=int32)

In [63]:
arr17=np.array([1,2,3,4,5],dtype='S')
arr17

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [66]:
arr18=np.array([1,2,3,4,5],dtype='U11')
arr18

array(['1', '2', '3', '4', '5'], dtype='<U11')

In [67]:
arr19=np.array([1,2,3,4,5],dtype='i')
arr19=arr19.astype('f')
arr19

array([1., 2., 3., 4., 5.], dtype=float32)

In [68]:
#Mean of an array
np.mean(arr19)

3.0

In [69]:
#Median of an array
np.median(arr19)

3.0

# Pandas

In [6]:
# Pandas
import pandas as pd
s=pd.Series([1,2,3,4,5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [75]:
s[2]

3

In [7]:
s.head(2) #First two values

0    1
1    2
dtype: int64

In [80]:
s.tail(2)  #Last two values

3    4
4    5
dtype: int64

In [8]:
s.tail(3)  #Last three values

2    3
3    4
4    5
dtype: int64

In [76]:
s2=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
s2

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [77]:
s2['c']

3

In [78]:
s3=pd.Series({"a":1,"b":2,"c":3,"d":4})
s3

a    1
b    2
c    3
d    4
dtype: int64

In [9]:
df=pd.DataFrame([1,2,3,4])
df

0
0  1
1  2
2  3
3  4

In [10]:
df2=pd.DataFrame({"Name":["John","Alfred","Rohit"],"City":["Lucknow","Kanpur","Mumbai"]})
df2

Name     City
0    John  Lucknow
1  Alfred   Kanpur
2   Rohit   Mumbai

In [89]:
df2["Name"]

0      John
1    Alfred
2     Rohit
Name: Name, dtype: object

In [11]:
df2[["Name","City"]]

Name     City
0    John  Lucknow
1  Alfred   Kanpur
2   Rohit   Mumbai

In [91]:
df2.iloc[1]  #Data of particular row --->fatching data of 2nd row

Name    Alfred
City    Kanpur
Name: 1, dtype: object

In [12]:
df3=pd.DataFrame({"Name":["John","Alfred","Rohit"],"City":["Lucknow","Kanpur","Mumbai"],"College":["10","13","17"]})
df3

Name     City College
0    John  Lucknow      10
1  Alfred   Kanpur      13
2   Rohit   Mumbai      17

# Adding new column

In [92]:

age=[23,24,25]
df2['age']=age
df2

Name     City  age
0    John  Lucknow   23
1  Alfred   Kanpur   24
2   Rohit   Mumbai   25

# Deleting a column

In [13]:
df2.drop(['City'],axis=1,inplace=True)
df2

Name
0    John
1  Alfred
2   Rohit

In [14]:
df2=df2.rename(columns={"Name":"imp_name"})
df2

imp_name
0     John
1   Alfred
2    Rohit

# Filling Null Values

In [4]:
import pandas as pd
import numpy as np
df=pd.DataFrame({"Name":["Aman","Rahul","Priya",np.nan],"age":[27,28,29,30]})
df.fillna("Ram",inplace=True)
df

Name  age
0   Aman   27
1  Rahul   28
2  Priya   29
3    Ram   30

# Dropping null values

In [5]:
#import panda as pd
df2=pd.DataFrame({"Name":["Aman","Rahul","Priya",np.nan],"age":[27,28,29,30]})
df2.dropna(inplace=True)
df2

Name  age
0   Aman   27
1  Rahul   28
2  Priya   29

# Adding a Row

In [8]:
new_row=pd.DataFrame({"Name":"Pooja","age":30},index=[0])
df2=pd.concat([df2,new_row]).reset_index(drop=True)
df2

Name  age
0   Aman   27
1  Rahul   28
2  Priya   29
3  Pooja   30
4  Pooja   30
5  Pooja   30

# Deleting a row

In [13]:
df2.drop(5,inplace=True)
df2

Name  age
0   Aman   27
1  Rahul   28
4  Pooja   30

# Iterating rows

In [14]:
for i,j in df2.iterrows():
    print(i)
    print(j)

0
Name    Aman
age       27
Name: 0, dtype: object
1
Name    Rahul
age        28
Name: 1, dtype: object
4
Name    Pooja
age        30
Name: 4, dtype: object


In [15]:
for i,j in df2.iteritems():
    print(i)
    print(j)

Name
0     Aman
1    Rahul
4    Pooja
Name: Name, dtype: object
age
0    27
1    28
4    30
Name: age, dtype: int64


/tmp/ipykernel_3216/619136569.py:1: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i,j in df2.iteritems():


# Iterating over columns

In [17]:
for column in df2:
    colvalue=df2[column]
    print(column)
    print(colvalue)

Name
0     Aman
1    Rahul
4    Pooja
Name: Name, dtype: object
age
0    27
1    28
4    30
Name: age, dtype: int64


In [18]:
for column in df2:
    colvalue=df2[column]
    print(column)
    print(colvalue.values)

Name
['Aman' 'Rahul' 'Pooja']
age
[27 28 30]


# Reading CSV DATA

In [21]:
df=pd.read_csv("/home/kali/Downloads/User_Data.csv")
df=pd.DataFrame(df)
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [23]:
df.head(10)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0
6  15598044  Female   27            84000          0
7  15694829  Female   32           150000          1
8  15600575    Male   25            33000          0
9  15727311  Female   35            65000          0

In [25]:
df.tail(10)

User ID  Gender  Age  EstimatedSalary  Purchased
390  15807837    Male   48            33000          1
391  15592570    Male   47            23000          1
392  15748589  Female   45            45000          1
393  15635893    Male   60            42000          1
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

# Finding total null values in the dataset

In [26]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

# fetch rhe rows having salary>30000 and purchased=1

In [28]:
df['EstimatedSalary']>30000

0      False
1      False
2       True
3       True
4       True
       ...  
395     True
396    False
397    False
398     True
399     True
Name: EstimatedSalary, Length: 400, dtype: bool

In [29]:
df[df['EstimatedSalary']>30000]

User ID  Gender  Age  EstimatedSalary  Purchased
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
5    15728773    Male   27            58000          0
6    15598044  Female   27            84000          0
..        ...     ...  ...              ...        ...
393  15635893    Male   60            42000          1
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[343 rows x 5 columns]

In [34]:
df[(df['EstimatedSalary']>30000) & (df['Purchased']==1)]

User ID  Gender  Age  EstimatedSalary  Purchased
7    15694829  Female   32           150000          1
21   15736760  Female   47            49000          1
22   15714658    Male   48            41000          1
31   15729054  Female   27           137000          1
48   15727696    Male   30           135000          1
..        ...     ...  ...              ...        ...
390  15807837    Male   48            33000          1
392  15748589  Female   45            45000          1
393  15635893    Male   60            42000          1
395  15691863  Female   46            41000          1
399  15594041  Female   49            36000          1

[123 rows x 5 columns]

# Value_counts()

In [35]:
df['Purchased'].value_counts()  #output shows that 0 is 257 times existing
                                #abd 1 is 143 times existing.

0    257
1    143
Name: Purchased, dtype: int64

In [36]:
df['Gender'].value_counts()

Female    204
Male      196
Name: Gender, dtype: int64

In [46]:
# Write a Pandas program to select the rows where the number of attempts in the examination is greater than 2.
# Sample Python dictionary data:
# exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
# 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
# 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
# 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

df5=pd.DataFrame({"Name":["Anastasia","Dima","Katherine","James","Emily","Michael","Matthew","Laura","Kevin","Jonas"],"Score":[12.5,9,16.5,np.nan,9,20,14.5,np.nan, 8, 19],"attempts": [1,3,2,3,2,3,1,1,2,1],"qualify": ["yes","no","yes","no","no","yes","yes","no","no","yes"]})
df5.drop(3,inplace=True)
df5.drop(7,inplace=True)
df5

Name  Score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes

In [48]:
df5

Name  Score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes

# Inserting DataFrame into Excel File

In [50]:
writer=pd.ExcelWriter("/home/kali/Downloads/output.xlsx")
df5.to_excel(writer)
writer.save()

/tmp/ipykernel_3216/3595056910.py:3: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()


In [47]:
df5[df5['attempts']>2]

Name  Score  attempts qualify
1     Dima    9.0         3      no
5  Michael   20.0         3     yes

In [54]:
#Write a Pandas program to calculate the sum of the examination attempts by the students.
df5["attempts"].value_counts()

1    3
2    3
3    2
Name: attempts, dtype: int64

In [57]:
df5["attempts"].sum()

15